################################################################################
#
################################################################################

apiVersion: batch/v1
kind: Job
metadata:
  name: always-succeeds
spec:
  backoffLimit: 0
  template:
    metadata:
      name: always-succeeds
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 120
      volumes:
        - name: func-tests
          persistentVolumeClaim:
            claimName: func-tests
      containers:
        - name: always-succeeds
          image: bash:5.0.17
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/bash
            - /mnt/func-tests/src/script/test/always_succeeds.sh
          volumeMounts:
            - name: func-tests
              mountPath: /mnt/func-tests
